---
name: Workflow-Run
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v3
        - run: |
            echo ${{ github.event.workflow_run.head_branch }}
