---
name: Workflow-Run
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v3
        - run: |
            echo ${{ github.ref_name }}
